name: Docker Image CI

on: [push]

jobs:

  build-and-deploy-i868:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file i868/Dockerfile --tag drakkarsoftware/octobot-pypi-deploy:i868

  
  build-and-deploy-x86_64:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file x86_64/Dockerfile --tag drakkarsoftware/octobot-pypi-deploy:x86_64
