name: Docker Image CI

on: [push]

jobs:

  build-and-deploy-i686:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file i686/Dockerfile --tag drakkarsoftware/octobot-pypi-deploy:i686
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: drakkarsoftware/octobot-pypi-deploy:i686
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: i686/Dockerfile
  
  build-and-deploy-x86_64:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file x86_64/Dockerfile --tag drakkarsoftware/octobot-pypi-deploy:x86_64
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: drakkarsoftware/octobot-pypi-deploy:x86_64
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: i686/Dockerfile
