name: Docker Image CI

on: [push]

jobs:

  build-and-deploy-i686:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file i686/Dockerfile --tag drakkarsoftware/octobot-pypi-deploy:i686

  
  build-and-deploy-x86_64:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file x86_64/Dockerfile --tag drakkarsoftware/octobot-pypi-deploy:x86_64
